server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bus_topup_db?charset=utf8mb4&parseTime=True&loc=Local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123

mybatis:
  type-aliases-package: com.bustopup.server.entity
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # 输出到 SLF4J

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
